import type { DialectSettings } from "./types";

export const mysqlSettings: DialectSettings = {
  id: "mysql",
  label: "MySQL",
  identifierQuote: "`",
  constraintWords: ["NOT", "NULL", "PRIMARY", "REFERENCES", "UNIQUE", "CHECK", "DEFAULT", "CONSTRAINT", "COLLATE", "GENERATED", "AUTO_INCREMENT", "COMMENT", "ON"],
  tableDefinitionWords: ["PRIMARY", "FOREIGN", "UNIQUE", "CHECK", "CONSTRAINT", "KEY", "INDEX", "FULLTEXT", "SPATIAL"],
  customTypeKinds: [],
  inlineValueTypes: ["enum", "set"],
  dataTypes: [
    { id: "tinyint", label: "TINYINT", category: "numeric", parameter: "length", supportsUnsigned: true, defaultParameters: { length: "10" } },
    { id: "smallint", label: "SMALLINT", category: "numeric", parameter: "length", supportsUnsigned: true, defaultParameters: { length: "10" } },
    { id: "mediumint", label: "MEDIUMINT", category: "numeric", parameter: "length", supportsUnsigned: true, defaultParameters: { length: "10" } },
    { id: "int", label: "INT", aliases: ["integer"], category: "numeric", parameter: "length", supportsUnsigned: true, defaultParameters: { length: "10" } },
    { id: "bigint", label: "BIGINT", category: "numeric", parameter: "length", supportsUnsigned: true, defaultParameters: { length: "10" } },
    { id: "decimal", label: "DECIMAL", aliases: ["numeric"], category: "numeric", parameter: "precision-scale", supportsUnsigned: true, defaultParameters: { precision: "10", scale: "2" } },
    { id: "float", label: "FLOAT", category: "numeric", parameter: "precision-scale", supportsUnsigned: true, defaultParameters: { precision: "10", scale: "2" } },
    { id: "double", label: "DOUBLE", category: "numeric", parameter: "precision-scale", supportsUnsigned: true, defaultParameters: { precision: "10", scale: "2" } },
    { id: "bit", label: "BIT", category: "binary", parameter: "length", defaultParameters: { length: "1" } },
    { id: "char", label: "CHAR", category: "text", parameter: "length", defaultParameters: { length: "255" } },
    { id: "varchar", label: "VARCHAR", category: "text", parameter: "length", defaultParameters: { length: "255" } },
    { id: "tinytext", label: "TINYTEXT", category: "text" },
    { id: "text", label: "TEXT", category: "text" },
    { id: "mediumtext", label: "MEDIUMTEXT", category: "text" },
    { id: "longtext", label: "LONGTEXT", category: "text" },
    { id: "binary", label: "BINARY", category: "binary", parameter: "length", defaultParameters: { length: "255" } },
    { id: "varbinary", label: "VARBINARY", category: "binary", parameter: "length", defaultParameters: { length: "255" } },
    { id: "blob", label: "BLOB", category: "binary" },
    { id: "boolean", label: "BOOLEAN", aliases: ["bool"], category: "boolean" },
    { id: "date", label: "DATE", category: "date-time" },
    { id: "time", label: "TIME", category: "date-time", parameter: "time-precision", defaultParameters: { length: "6" } },
    { id: "datetime", label: "DATETIME", category: "date-time", parameter: "time-precision", defaultParameters: { length: "6" } },
    { id: "timestamp", label: "TIMESTAMP", category: "date-time", parameter: "time-precision", defaultParameters: { length: "6" } },
    { id: "year", label: "YEAR", category: "date-time" },
    { id: "json", label: "JSON", category: "json" },
    { id: "enum", label: "ENUM", category: "text", parameter: "values", defaultParameters: { values: ["value_1", "value_2"] } },
    { id: "set", label: "SET", category: "text", parameter: "values", defaultParameters: { values: ["value_1", "value_2"] } },
  ],
};
