import type { DialectSettings } from "./types";

export const postgresqlSettings: DialectSettings = {
  id: "postgresql",
  label: "PostgreSQL",
  identifierQuote: '"',
  constraintWords: ["NOT", "NULL", "PRIMARY", "REFERENCES", "UNIQUE", "CHECK", "DEFAULT", "CONSTRAINT", "COLLATE", "GENERATED", "IDENTITY", "ON"],
  tableDefinitionWords: ["PRIMARY", "FOREIGN", "UNIQUE", "CHECK", "EXCLUDE", "CONSTRAINT"],
  customTypeKinds: ["enum", "domain", "composite"],
  inlineValueTypes: [],
  dataTypes: [
    { id: "smallint", label: "SMALLINT", aliases: ["int2"], category: "numeric", supportsArray: true },
    { id: "integer", label: "INTEGER", aliases: ["int", "int4"], category: "numeric", supportsArray: true },
    { id: "bigint", label: "BIGINT", aliases: ["int8"], category: "numeric", supportsArray: true },
    { id: "smallserial", label: "SMALLSERIAL", aliases: ["serial2"], category: "numeric" },
    { id: "serial", label: "SERIAL", aliases: ["serial4"], category: "numeric" },
    { id: "bigserial", label: "BIGSERIAL", aliases: ["serial8"], category: "numeric" },
    { id: "numeric", label: "NUMERIC", aliases: ["decimal"], category: "numeric", parameter: "precision-scale", supportsArray: true, defaultParameters: { precision: "10", scale: "2" } },
    { id: "real", label: "REAL", aliases: ["float4"], category: "numeric", supportsArray: true },
    { id: "double precision", label: "DOUBLE PRECISION", aliases: ["float8"], category: "numeric", supportsArray: true },
    { id: "money", label: "MONEY", category: "numeric", supportsArray: true },
    { id: "varchar", label: "VARCHAR", aliases: ["character varying"], category: "text", parameter: "length", supportsArray: true, defaultParameters: { length: "255" } },
    { id: "char", label: "CHAR", aliases: ["character"], category: "text", parameter: "length", supportsArray: true, defaultParameters: { length: "255" } },
    { id: "text", label: "TEXT", category: "text", supportsArray: true },
    { id: "boolean", label: "BOOLEAN", aliases: ["bool"], category: "boolean", supportsArray: true },
    { id: "date", label: "DATE", category: "date-time", supportsArray: true },
    { id: "time", label: "TIME", category: "date-time", parameter: "time-precision", supportsArray: true, defaultParameters: { length: "6" } },
    { id: "timestamp", label: "TIMESTAMP", category: "date-time", parameter: "time-precision", supportsArray: true, defaultParameters: { length: "6" } },
    { id: "timestamptz", label: "TIMESTAMPTZ", aliases: ["timestamp with time zone"], category: "date-time", parameter: "time-precision", supportsArray: true, defaultParameters: { length: "6" } },
    { id: "interval", label: "INTERVAL", category: "date-time", supportsArray: true },
    { id: "bytea", label: "BYTEA", category: "binary", supportsArray: true },
    { id: "json", label: "JSON", category: "json", supportsArray: true },
    { id: "jsonb", label: "JSONB", category: "json", supportsArray: true },
    { id: "uuid", label: "UUID", category: "other", supportsArray: true },
    { id: "inet", label: "INET", category: "network", supportsArray: true },
    { id: "cidr", label: "CIDR", category: "network", supportsArray: true },
    { id: "macaddr", label: "MACADDR", category: "network", supportsArray: true },
    { id: "bit", label: "BIT", category: "binary", parameter: "length", supportsArray: true, defaultParameters: { length: "1" } },
    { id: "varbit", label: "VARBIT", aliases: ["bit varying"], category: "binary", parameter: "length", supportsArray: true, defaultParameters: { length: "255" } },
    { id: "xml", label: "XML", category: "other", supportsArray: true },
  ],
};
