import { useMemo, useRef, useState } from "react";
import type { PointerEvent as ReactPointerEvent } from "react";
import { layoutRoutineFlow } from "../../domain/flowLayout";
import { parseRoutineFlow } from "../../domain/routineFlow";
import type { Routine } from "../../domain/types";
import { FlowBlock } from "./FlowBlock";
import { FlowConnections, flowAnimationOrder, reachableFlow } from "./FlowConnections";
import { useFlowGeometry } from "./useFlowGeometry";

export function InlineRoutineFlow({ routine, origin, scale, onCollapse }: { routine: Routine; origin: { x: number; y: number }; scale: number; onCollapse: () => void }) {
  const flow = useMemo(() => parseRoutineFlow(routine.id, routine.body), [routine.id, routine.body]); const automatic = useMemo(() => layoutRoutineFlow(flow, origin), [flow, origin.x, origin.y]); const [manual, setManual] = useState<Map<string, { x: number; y: number }>>(new Map()); const [pinned, setPinned] = useState<Set<string>>(new Set()); const [focus, setFocus] = useState<{ nodeId: string; portId: string } | null>(null); const [selected, setSelected] = useState<string | null>(null); const drag = useRef<{ id: string; px: number; py: number; x: number; y: number } | null>(null); const stageRef = useRef<HTMLDivElement>(null); const geometry = useFlowGeometry(stageRef, manual, scale); const positions = new Map(automatic); manual.forEach((point, id) => positions.set(id, point)); const focused = focus ? reachableFlow(flow, focus.nodeId, focus.portId) : null; const animationOrder = useMemo(() => focus ? flowAnimationOrder(flow, focus.nodeId, focus.portId) : selected ? flowAnimationOrder(flow, selected) : null, [flow, focus, selected]);
  const start = (event: ReactPointerEvent, id: string) => { event.stopPropagation(); const point = positions.get(id)!; drag.current = { id, px: event.clientX, py: event.clientY, x: point.x, y: point.y }; event.currentTarget.setPointerCapture(event.pointerId); };
  const move = (event: ReactPointerEvent) => { if (!drag.current) return; const current = drag.current; setManual((values) => new Map(values).set(current.id, { x: current.x + event.clientX - current.px, y: current.y + event.clientY - current.py })); };
  const finish = () => { if (!drag.current) return; const id = drag.current.id; drag.current = null; setPinned((values) => new Set(values).add(id)); };
  return <div ref={stageRef} className="inline-routine-flow" onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}><div className="inline-routine-label" style={{ left: origin.x, top: origin.y }}><strong>{routine.schema ? `${routine.schema}.` : ""}{routine.name}</strong><button onClick={onCollapse}>Collapse flow</button></div><FlowConnections key={focus ? `${focus.nodeId}:${focus.portId}` : selected ?? "idle"} flow={flow} positions={positions} focusedEdges={focused?.edges ?? null} animationOrder={animationOrder} portCenters={geometry.centers}/>{flow.nodes.map((node) => <FlowBlock key={node.id} node={node} position={positions.get(node.id)!} selected={selected === node.id} dimmed={Boolean(focused && !focused.nodes.has(node.id))} pinned={pinned.has(node.id)} onSelect={() => { setSelected((value) => value === node.id ? null : node.id); setFocus(null); }} onDragStart={start} onPortFocus={(nodeId, portId) => setFocus((value) => value?.nodeId === nodeId && value.portId === portId ? null : { nodeId, portId })} registerPort={geometry.registerPort}/>)}</div>;
}
